version: "3.9"

services:
  api:
    container_name: peerly-api-prod
    build:
      context: .
      dockerfile: Dockerfile.api.prod
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=8082
    expose:
      - "8082"
    ports:
      - "8082:8082"

  web:
    container_name: peerly-web-prod
    build:
      context: .
      dockerfile: Dockerfile.web.prod
      args:
        # Optional: override during build if you need absolute API base at build time
        # VITE_API_BASE: 
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    depends_on:
      - api
