version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: peerly-postgres
    environment:
      POSTGRES_USER: peerly_user
      POSTGRES_PASSWORD: peerly_password
      POSTGRES_DB: peerly_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U peerly_user -d peerly_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: peerly-monolith
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      # Docker Compose network hostname for postgres is 'db'
      - DATABASE_URL=postgres://peerly_user:peerly_password@db:5432/peerly_db?sslmode=disable
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
