version: "3.9"

services:
  api:
    container_name: peerly-api-prod
    build:
      context: .
      dockerfile: Dockerfile.api.prod
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=8082
    expose:
      - "8082"
    ports:
      - "8082:8082"

  web:
    container_name: peerly-web-prod
    build:
      context: .
      dockerfile: Dockerfile.web.prod
      args:
        # Inject Vite envs at build-time from .env
        VITE_API_BASE: ${VITE_API_BASE}
        VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
        VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
        VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
        VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    depends_on:
      - api
