package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"

	"peerly.dev/backend/gateway/graph/model"
	"peerly.dev/backend/gateway/middleware"
	"peerly.dev/backend/proto/authpb"
	"peerly.dev/backend/proto/userpb"
)

// LoginWithFirebase is the resolver for the loginWithFirebase field.
func (r *mutationResolver) LoginWithFirebase(ctx context.Context, idToken string) (*model.AuthResponse, error) {
	resp, err := r.AuthClient.VerifyFirebaseToken(ctx, &authpb.VerifyFirebaseTokenRequest{
		IdToken: idToken,
	})
	if err != nil {
		return nil, err
	}
	return &model.AuthResponse{
		AccessToken: resp.AccessToken,
		ExpiresIn:   int(resp.ExpiresIn),
		UserID:      resp.UserId,
	}, nil
}

// RegisterNative is the resolver for the registerNative field.
func (r *mutationResolver) RegisterNative(ctx context.Context, input model.RegisterInput) (*model.AuthResponse, error) {
	resp, err := r.AuthClient.RegisterUser(ctx, &authpb.RegisterUserRequest{
		Email:       input.Email,
		Password:    input.Password,
		DisplayName: input.DisplayName,
	})
	if err != nil {
		return nil, err
	}
	return &model.AuthResponse{
		AccessToken: resp.AccessToken,
		ExpiresIn:   int(resp.ExpiresIn),
		UserID:      resp.UserId,
	}, nil
}

// LoginNative is the resolver for the loginNative field.
func (r *mutationResolver) LoginNative(ctx context.Context, input model.LoginInput) (*model.AuthResponse, error) {
	resp, err := r.AuthClient.LoginUser(ctx, &authpb.LoginUserRequest{
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}
	return &model.AuthResponse{
		AccessToken: resp.AccessToken,
		ExpiresIn:   int(resp.ExpiresIn),
		UserID:      resp.UserId,
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context) (*model.AuthResponse, error) {
	// In reality, extract the HTTP-only cookie here. For the skeleton, pass empty string.
	resp, err := r.AuthClient.RefreshToken(ctx, &authpb.RefreshTokenRequest{RefreshToken: ""})
	if err != nil {
		return nil, err
	}
	return &model.AuthResponse{
		AccessToken: resp.AccessToken,
		ExpiresIn:   int(resp.ExpiresIn),
		UserID:      resp.UserId,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	resp, err := r.AuthClient.Logout(ctx, &authpb.LogoutRequest{RefreshToken: ""})
	if err != nil {
		return false, err
	}
	return resp.Success, nil
}

// UpsertProfile is the resolver for the upsertProfile field.
func (r *mutationResolver) UpsertProfile(ctx context.Context, input model.UpsertProfileInput) (*model.Profile, error) {
	userIdVal := ctx.Value(middleware.SubContextKey)
	if userIdVal == nil {
		return nil, fmt.Errorf("unauthenticated")
	}
	userID := userIdVal.(string)

	resp, err := r.UserClient.UpsertProfile(ctx, &userpb.UpsertProfileRequest{
		UserId:      userID,
		DisplayName: *input.DisplayName,
		Bio:         *input.Bio,
	})
	if err != nil {
		return nil, err
	}
	return &model.Profile{
		DisplayName: &resp.DisplayName,
		Bio:         &resp.Bio,
		AvatarURL:   &resp.AvatarUrl,
	}, nil
}

// SetRole is the resolver for the setRole field.
func (r *mutationResolver) SetRole(ctx context.Context, role model.Role) (bool, error) {
	userIdVal := ctx.Value(middleware.SubContextKey)
	if userIdVal == nil {
		return false, fmt.Errorf("unauthenticated")
	}
	userID := userIdVal.(string)

	_, err := r.AuthClient.SetRole(ctx, &authpb.SetRoleRequest{
		UserId: userID,
		Role:   string(role),
	})
	if err != nil {
		return false, err
	}
	return true, nil
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "pong", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userIdVal := ctx.Value(middleware.SubContextKey)
	if userIdVal == nil {
		return nil, fmt.Errorf("unauthenticated")
	}
	userID := userIdVal.(string)

	resp, err := r.UserClient.GetUser(ctx, &userpb.GetUserRequest{UserId: userID})
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:    resp.Id,
		Email: resp.Email,
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	resp, err := r.UserClient.GetUser(ctx, &userpb.GetUserRequest{UserId: id})
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:    resp.Id,
		Email: resp.Email,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
