package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"

	"peerly.dev/backend/graph/model"
	"peerly.dev/backend/middleware"
)

// LoginWithFirebase is the resolver for the loginWithFirebase field.
func (r *mutationResolver) LoginWithFirebase(ctx context.Context, idToken string) (*model.AuthResponse, error) {
	resp, err := r.AuthService.VerifyFirebaseToken(ctx, idToken)
	if err != nil {
		return nil, err
	}
	return &model.AuthResponse{
		AccessToken: resp.AccessToken,
		ExpiresIn:   int(resp.ExpiresIn),
		UserID:      resp.UserID,
	}, nil
}

// RegisterNative is the resolver for the registerNative field.
func (r *mutationResolver) RegisterNative(ctx context.Context, input model.RegisterInput) (*model.AuthResponse, error) {
	resp, err := r.AuthService.RegisterUser(ctx, input.Email, input.Password, input.DisplayName)
	if err != nil {
		return nil, err
	}
	return &model.AuthResponse{
		AccessToken: resp.AccessToken,
		ExpiresIn:   int(resp.ExpiresIn),
		UserID:      resp.UserID,
	}, nil
}

// LoginNative is the resolver for the loginNative field.
func (r *mutationResolver) LoginNative(ctx context.Context, input model.LoginInput) (*model.AuthResponse, error) {
	resp, err := r.AuthService.LoginUser(ctx, input.Email, input.Password)
	if err != nil {
		return nil, err
	}
	return &model.AuthResponse{
		AccessToken: resp.AccessToken,
		ExpiresIn:   int(resp.ExpiresIn),
		UserID:      resp.UserID,
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context) (*model.AuthResponse, error) {
	// TODO: implement real refresh-token logic (read HTTP-only cookie, validate, re-issue)
	return nil, fmt.Errorf("refresh token not yet implemented")
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	// TODO: revoke the refresh token stored in the HTTP-only cookie
	return true, nil
}

// UpsertProfile is the resolver for the upsertProfile field.
func (r *mutationResolver) UpsertProfile(ctx context.Context, input model.UpsertProfileInput) (*model.Profile, error) {
	userIDVal := ctx.Value(middleware.SubContextKey)
	if userIDVal == nil {
		return nil, fmt.Errorf("unauthenticated")
	}
	userID := userIDVal.(string)

	displayName := ""
	if input.DisplayName != nil {
		displayName = *input.DisplayName
	}
	bio := ""
	if input.Bio != nil {
		bio = *input.Bio
	}

	resp, err := r.UserService.UpsertProfile(ctx, userID, displayName, bio)
	if err != nil {
		return nil, err
	}
	return &model.Profile{
		DisplayName: &resp.DisplayName,
		Bio:         &resp.Bio,
		AvatarURL:   &resp.AvatarURL,
	}, nil
}

// SetRole is the resolver for the setRole field.
func (r *mutationResolver) SetRole(ctx context.Context, role model.Role) (bool, error) {
	userIDVal := ctx.Value(middleware.SubContextKey)
	if userIDVal == nil {
		return false, fmt.Errorf("unauthenticated")
	}
	userID := userIDVal.(string)

	if err := r.AuthService.SetRole(ctx, userID, string(role)); err != nil {
		return false, err
	}
	return true, nil
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "pong", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userIDVal := ctx.Value(middleware.SubContextKey)
	if userIDVal == nil {
		return nil, fmt.Errorf("unauthenticated")
	}
	userID := userIDVal.(string)

	u, err := r.UserService.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	roles := make([]model.Role, 0, len(u.Roles))
	for _, r := range u.Roles {
		roles = append(roles, model.Role(r))
	}

	googleID := u.GoogleID
	return &model.User{
		ID:       u.ID,
		Email:    u.Email,
		GoogleID: &googleID,
		Roles:    roles,
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	u, err := r.UserService.GetUser(ctx, id)
	if err != nil {
		return nil, err
	}

	roles := make([]model.Role, 0, len(u.Roles))
	for _, r := range u.Roles {
		roles = append(roles, model.Role(r))
	}

	googleID := u.GoogleID
	return &model.User{
		ID:       u.ID,
		Email:    u.Email,
		GoogleID: &googleID,
		Roles:    roles,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
